sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo pip install catkin_pkg
  - sudo pip install empy
  - sudo pip install pyyaml
  - sudo pip install rospkg

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_prepare_dummy_files.bash
  - rostest pimouse_run_corridor  wall_stop.launch

